FROM {{ image_base }}

{% for user_lib in user_baselibs %}
ADD .user-baselibs/{{ user_lib }} /app/{{ user_lib }}
RUN cd /app/{{ user_lib }} && test -f requirements.txt && pip3 install -r requirements.txt || echo "no reqs for {{ user_lib }}"
{% endfor %}

{% for source in sources %}
ADD {{ source.origin }} {{ source.destination }}
{% endfor %}

RUN pip install requests

#RUN pip install poetry
#RUN cd cm-client && poetry lock && poetry install
RUN pip install krules-companion-client==0.9.10
RUN pip install ipython


RUN pip install --no-cache-dir \
    krules-fastapi-env==0.12.1 \
    krules-dispatcher-cloudevents-pubsub==0.12.0 \
    krules-subjects-storage-redis==0.12.0

#RUN pip install --no-cache-dir google-cloud-pubsub==2.19.6

{## requirement for quote-indicators library#}
{## Add Microsoft package repository#}
{#RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \#}
{#    && dpkg -i packages-microsoft-prod.deb \#}
{#    && rm packages-microsoft-prod.deb#}
{##}
{## Install .NET SDK#}
{#RUN apt-get update \#}
{#    && DEBIAN_FRONTEND=noninteractive apt-get install -y apt-transport-https \#}
{#    && apt-get update \#}
{#    && DEBIAN_FRONTEND=noninteractive apt-get install -y dotnet-sdk-6.0#}

RUN pip install rich

CMD celery -A tasks worker --loglevel=INFO