FROM {{ image_base }}

{% for user_lib in user_baselibs %}
ADD .user-baselibs/{{ user_lib }} /app/{{ user_lib }}
RUN cd /app/{{ user_lib }} && test -f requirements.txt && pip3 install -r requirements.txt || echo "no reqs for {{ user_lib }}"
{% endfor %}

{% for source in sources %}
ADD {{ source.origin }} {{ source.destination }}
{% endfor %}

RUN pip install requests

#RUN pip install poetry
#RUN cd cm-client && poetry lock && poetry install
RUN pip install krules-companion-client==0.9.2
RUN pip install ipython

# TODO...
RUN pip install --no-cache-dir --no-deps \
    cloudevents==1.10.1 \
    google-auth==2.28.1 \
    google-api-core==2.17.1 \
    google-cloud-pubsub==2.19.6 \
    google-cloud-secret-manager==2.18.2 \
    protobuf==4.25.3 \
    grpcio==1.62.0 \
    ;
RUN pip install --no-cache-dir google-cloud-pubsub==2.19.6


RUN pip install pandas-ta

CMD celery -A tasks worker --loglevel=INFO