strategy:
  is_mock_strategy: true
  reset_limit_on_exit: false         # DEPRECATED
  outer_limit_follows: ema_100_H     # DEPRECATED

  session:
    strategies:
      - strategy: limit
        kwargs:
          name: limit_ema_100_H
        groups:
          - open
          - bound
      - strategy: limit
        kwargs:
          name: limit_ema_100_4H
        groups:
          - open
          - bound
      - strategy: ema
        kwargs:
          interval: T
          period: 100
        groups:
          - open
          - close
      - strategy: supertrend
        kwargs:
          interval: T
        groups:
          - open
          - close
      - strategy: supertrend_dir
        kwargs:
          interval: T
        groups:
          - open

  limits:
  - name: limit_ema_100_H
    follows: ema_100_H
    reset_on_action: if_none
  - name: limit_ema_100_4H
    follows: ema_100_4H
    reset_on_action: if_none



symbol:
  provider: bybit
  category: linear
  name: btcusdt