strategy:
  is_mock_strategy: true

  session:
    strategies:
      - strategy: limit
        kwargs:
          name: limit_ema_100_H
        groups:
          - open
          - bound
      - strategy: ema
        kwargs:
          interval: 4H
          period: 100
        groups:
          - open
          - bound
#      - strategy: ema
#        kwargs:
#          interval: T
#          period: 100
#        groups:
#          - open
#          - close
      - strategy: supertrend
        kwargs:
          interval: T
        groups:
          - open
          - close
      - strategy: supertrend_dir
        kwargs:
          interval: T
        groups:
          - open

  limits:
    - follows: ema_100_H




symbol:
  provider: bybit
  category: linear
  name: btcusdt