FROM {{ image_base }}

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update --yes && \
    # - `apt-get upgrade` is run to patch known vulnerabilities in system packages
    #   as the Ubuntu base image is rebuilt too seldom sometimes (less than once a month)
    apt-get upgrade --yes && \
    apt-get install --yes --no-install-recommends \
    # - bzip2 is necessary to extract the micromamba executable.
    bzip2 \
    ca-certificates \
    locales \
    sudo \
    # - `tini` is installed as a helpful container entrypoint,
    #   that reaps zombie processes and such of the actual executable we want to start
    #   See https://github.com/krallin/tini#why-tini for details
    tini \
    wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    # - Add necessary fonts for matplotlib/seaborn
    #   See https://github.com/jupyter/docker-stacks/pull/380 for details
    fonts-liberation \
    # - `pandoc` is used to convert notebooks to html files
    #   it's not present in the aarch64 Ubuntu image, so we install it here
    pandoc
    # - `run-one` - a wrapper script that runs no more
    #   than one unique instance of some command with a unique set of arguments,
    #   we use `run-one-constantly` to support the `RESTARTABLE` option
    # run-one && \
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
  jupyterlab \
  notebook \
  jupyterhub \
  nbclassic && \
  jupyter server --generate-config && \
  jupyter lab clean

ENV JUPYTER_PORT=8888
EXPOSE $JUPYTER_PORT

CMD ["jupyter", "lab"]

{% for user_lib in user_baselibs %}
ADD .user-baselibs/{{ user_lib }} /app/{{ user_lib }}
RUN cd /app/{{ user_lib }} && test -f requirements.txt && pip3 install -r requirements.txt || echo "no reqs for {{ user_lib }}"
{% endfor %}


{% for source in sources %}
ADD {{ source.origin }} {{ source.destination }}
{% endfor %}


# !! I loose deps somewhere
RUN pip install --no-cache-dir --no-deps \
    cloudevents==1.10.1 \
    google-auth==2.28.1 \
    google-api-core==2.17.1 \
    google-cloud-secret-manager==2.18.2 \
    protobuf==4.25.3 \
    grpcio==1.62.0 \
    ;
RUN pip install --no-cache-dir google-cloud-pubsub==2.19.6

RUN pip install pandas-ta

#HEALTHCHECK --interval=3s --timeout=1s --start-period=3s --retries=3 \
#    CMD /etc/jupyter/docker_healthcheck.py || exit 1

WORKDIR /root/work

