strategy:
  is_mock_strategy: true
  leverage: 1

  session:
    strategies:
      - strategy: limit
        kwargs:
          name: limit_top
        groups:
          - open
          - bound
      - strategy: supertrend
        kwargs:
          interval: H
        groups:
          - open
          - close
      - strategy: supertrend
        kwargs:
          interval: 15T
        groups:
          - open
          - close
      - strategy: supertrend
        kwargs:
          interval: T
        groups:
          - open
          - close
      - strategy: supertrend_dir
        kwargs:
          interval: T
        groups:
          - open


  limits:
  - name: limit_top
    follows: ema_100_4H
    engage: always
    reset_on_action: if_none



symbol:
  provider: bybit
  category: linear
  name: solusdt